In [ ]:
# prompt: Quero que leia o arquivo dados.csv

import pandas as pd

# Certifique-se de que o arquivo 'dados.csv' esteja no mesmo diretório do notebook ou forneça o caminho completo.

df = pd.read_csv('respostasForms.csv')
print(df.head()) # Exibe as primeiras linhas do DataFrame para verificar se a leitura foi bem-sucedida

  Carimbo de data/hora  Pontuação  \
0  14/11/2024 16:18:57        NaN
1  16/12/2024 17:03:06        NaN
2  16/12/2024 17:05:19        NaN
3  16/12/2024 17:10:19        NaN
4  16/12/2024 17:50:56        NaN

  Diante das explicações você acha que está suficientemente informado(a) a respeito da pesquisa que será realizada e concorda de livre e espontânea vontade em participar, como colaborador ?  \
0                                                Sim
1                                                Sim
2                                                Sim
3                                                Sim
4                                                Sim

   Qual a sua idade? Qual sua identidade de gênero?  \
0                 76                      Homem Cis
1                 23                      Homem Cis
2                 21                     Mulher Cis
3                 21                     Mulher Cis
4                 19                     Mulher Cis

  Em que estado você viveu a maior parte da sua vida?  \
0                                         Pernambuco
1                                     Rio de Janeiro
2                                     Rio de Janeiro
3                                     Rio de Janeiro
4                                     Rio de Janeiro

  Em que estado você vive atualmente?  \
0                      Rio de Janeiro
1                      Rio de Janeiro
2                      Rio de Janeiro
3                      Rio de Janeiro
4                      Rio de Janeiro

  Selecione uma lista para preencher, de preferencia o primeiro item da lista para garantir a aleatoriedade na metodologia.  \
0                                            Lista 3
1                                           Lista 10
2                                            Lista 2
3                                            Lista 4
4                                            Lista 1

  O renê matou todo momento do time cara, que loco filho da puta  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                             Não considero misógina

  “…Na boca de quem não presta\n Pomba gira é vagabunda…”  ...  \
0                                                NaN       ...
1                                                NaN       ...
2                                                NaN       ...
3                                                NaN       ...
4                             Não considero misógina       ...

  não gosta de mim por causa de homem já sei que é vagabunda  \
0                                                NaN
1                                 Considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

  ai gente foda se a militância chamem a vanessa lopes de vagabunda comigoooo  \
0                                                NaN
1                                 Considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

  você eh uma VAGABUNDA você eh uma DESALMADA você eh um CAPETA DEMONIO INFERNO  \
0                                                NaN
1                                 Considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

  “ain sério msm que o flamengo quer falar de roubo” sim piranha e quando roubarem o teu time vc fala do seu ô insuportável do caralho  \
0                                                NaN
1                                 Considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

  Mermao, pessoal ainda tá achando que a Madonna doou 10 milhões\n \n O próprio cara que inventou isso já desmentiu\n \n A Madonna não doou absolutamente NADA, tratou td mundo mal no hotel, falou mal dos brasileiros, pegou os milhões dela e METEU O PÉ\n \n Para de idolatrar essa VACA  \
0                                                NaN
1                                 Considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

  Ué, a galinha mineira jogou o clássico contra o Cruzeiro pelo brasileiro e está jogando contra o Peñarol pela libertadores e não poupou ninguém??  \
0                                                NaN
1                             Não considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

  Lula , Pacheco e essa gangue que ocupou a República tinham de ser recebidos com chuva de merda de vaca e lama pelo povo do Sul.\n Vão la fazer populismo com a\n Desgraça das pessoas.\n A real ? Esse canalhas não estão nem aí.\n Só com a imagem pro Jornal Nacional.  \
0                                                NaN
1                             Não considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

  tem umas fubangas nesse fandom que fazem esforço pra fingir que gostam do justin pq não é possível que você vai conseguir ser uma vaca egoista pra pensar em show e reclamar sobre show enquanto o homem ta virando PAI  \
0                                                NaN
1                                 Considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

  Não aguento mais tanto sofrimento com Tião Galinha e Joaninha  \
0                                                NaN
1                             Não considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

  O VAR SO EXISTE CONTRA O VITÓRIA, INCRÍVEL. \n \n CBF vagabunda
0                                                NaN
1                             Não considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

[5 rows x 308 columns]

In [ ]:
df_de_para = pd.read_excel('de_para.xlsx')
print(df_de_para.head()) # Exibe as primeiras linhas do DataFrame para verificar se a leitura foi bem-sucedida

   Palavra                                              Tweet
0  Baranga  essas baranga enchendo o saco a dias, não tem ...
1  Baranga  Yasmin disse q vai continuar com rodriguinho e...
2  Baranga  um fake veio me xingar me chamando de baranga ...
3  Baranga  fica usando time de futebol pra se sexualizar,...
4  Baranga  se fosse bonita e gostosa andava comigo e com ...

In [ ]:
# prompt: quero analise a df anterior, terá uma coluna nesse dataset chamada "Selecione uma lista para preencher, de preferencia o primeiro item da lista para garantir a aleatoriedade na metodologia.", é a oitava coluna. Com essa coluna quero que faça um filtro removendo toda ocorrência de resposta igual após a 5 aparição, levando sempre em consideração a ordem de registro da linha (informação encontrada na primeira coluna "Carimbo de data/hora"). Esclarecendo, por exemplo, se na linha 25 temos a aparição do valor "Lista 5" na coluna analisada pela quinta vez, todas as próximas aparições com esse mesmo valor será removido do dataset, por ordem de preenchimento.

# Mapear os nomes das colunas para facilitar o acesso
coluna_selecao = "Selecione uma lista para preencher, de preferencia o primeiro item da lista para garantir a aleatoriedade na metodologia."
coluna_timestamp = "Carimbo de data/hora"

# Converter a coluna de timestamp para datetime para garantir a ordem correta
df[coluna_timestamp] = pd.to_datetime(df[coluna_timestamp])

# Ordenar o DataFrame pelo timestamp
df = df.sort_values(by=coluna_timestamp)

# Dicionário para contar a ocorrência de cada valor na coluna de seleção
contagem_valores = {}

# Lista para armazenar os índices das linhas a serem removidas
indices_para_remover = []

# Iterar sobre as linhas do DataFrame
for index, row in df.iterrows():
    valor_selecao = row[coluna_selecao]

    # Incrementar a contagem do valor
    contagem_valores[valor_selecao] = contagem_valores.get(valor_selecao, 0) + 1

    # Se a contagem for maior que 5, adicionar o índice para remoção
    if contagem_valores[valor_selecao] > 5:
        indices_para_remover.append(index)

# Remover as linhas com base nos índices coletados
df_filtrado = df.drop(indices_para_remover)

# Exibir as primeiras linhas do DataFrame filtrado para verificar o resultado
print("\nDataFrame após o filtro:")
print(df_filtrado.head())

# Opcional: Você pode querer resetar o índice do novo DataFrame
df_filtrado = df_filtrado.reset_index(drop=True)
print("\nDataFrame após resetar o índice:")
print(df_filtrado.head())

DataFrame após o filtro:
  Carimbo de data/hora  Pontuação  \
0  2024-11-14 16:18:57        NaN
1  2024-12-16 17:03:06        NaN
2  2024-12-16 17:05:19        NaN
3  2024-12-16 17:10:19        NaN
4  2024-12-16 17:50:56        NaN

  Diante das explicações você acha que está suficientemente informado(a) a respeito da pesquisa que será realizada e concorda de livre e espontânea vontade em participar, como colaborador ?  \
0                                                Sim
1                                                Sim
2                                                Sim
3                                                Sim
4                                                Sim

   Qual a sua idade? Qual sua identidade de gênero?  \
0                 76                      Homem Cis
1                 23                      Homem Cis
2                 21                     Mulher Cis
3                 21                     Mulher Cis
4                 19                     Mulher Cis

  Em que estado você viveu a maior parte da sua vida?  \
0                                         Pernambuco
1                                     Rio de Janeiro
2                                     Rio de Janeiro
3                                     Rio de Janeiro
4                                     Rio de Janeiro

  Em que estado você vive atualmente?  \
0                      Rio de Janeiro
1                      Rio de Janeiro
2                      Rio de Janeiro
3                      Rio de Janeiro
4                      Rio de Janeiro

  Selecione uma lista para preencher, de preferencia o primeiro item da lista para garantir a aleatoriedade na metodologia.  \
0                                            Lista 3
1                                           Lista 10
2                                            Lista 2
3                                            Lista 4
4                                            Lista 1

  O renê matou todo momento do time cara, que loco filho da puta  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                             Não considero misógina

  “…Na boca de quem não presta\n Pomba gira é vagabunda…”  ...  \
0                                                NaN       ...
1                                                NaN       ...
2                                                NaN       ...
3                                                NaN       ...
4                             Não considero misógina       ...

  não gosta de mim por causa de homem já sei que é vagabunda  \
0                                                NaN
1                                 Considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

  ai gente foda se a militância chamem a vanessa lopes de vagabunda comigoooo  \
0                                                NaN
1                                 Considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

  você eh uma VAGABUNDA você eh uma DESALMADA você eh um CAPETA DEMONIO INFERNO  \
0                                                NaN
1                                 Considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

  “ain sério msm que o flamengo quer falar de roubo” sim piranha e quando roubarem o teu time vc fala do seu ô insuportável do caralho  \
0                                                NaN
1                                 Considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

  Mermao, pessoal ainda tá achando que a Madonna doou 10 milhões\n \n O próprio cara que inventou isso já desmentiu\n \n A Madonna não doou absolutamente NADA, tratou td mundo mal no hotel, falou mal dos brasileiros, pegou os milhões dela e METEU O PÉ\n \n Para de idolatrar essa VACA  \
0                                                NaN
1                                 Considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

  Ué, a galinha mineira jogou o clássico contra o Cruzeiro pelo brasileiro e está jogando contra o Peñarol pela libertadores e não poupou ninguém??  \
0                                                NaN
1                             Não considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

  Lula , Pacheco e essa gangue que ocupou a República tinham de ser recebidos com chuva de merda de vaca e lama pelo povo do Sul.\n Vão la fazer populismo com a\n Desgraça das pessoas.\n A real ? Esse canalhas não estão nem aí.\n Só com a imagem pro Jornal Nacional.  \
0                                                NaN
1                             Não considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

  tem umas fubangas nesse fandom que fazem esforço pra fingir que gostam do justin pq não é possível que você vai conseguir ser uma vaca egoista pra pensar em show e reclamar sobre show enquanto o homem ta virando PAI  \
0                                                NaN
1                                 Considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

  Não aguento mais tanto sofrimento com Tião Galinha e Joaninha  \
0                                                NaN
1                             Não considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

  O VAR SO EXISTE CONTRA O VITÓRIA, INCRÍVEL. \n \n CBF vagabunda
0                                                NaN
1                             Não considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

[5 rows x 308 columns]

DataFrame após resetar o índice:
  Carimbo de data/hora  Pontuação  \
0  2024-11-14 16:18:57        NaN
1  2024-12-16 17:03:06        NaN
2  2024-12-16 17:05:19        NaN
3  2024-12-16 17:10:19        NaN
4  2024-12-16 17:50:56        NaN

  Diante das explicações você acha que está suficientemente informado(a) a respeito da pesquisa que será realizada e concorda de livre e espontânea vontade em participar, como colaborador ?  \
0                                                Sim
1                                                Sim
2                                                Sim
3                                                Sim
4                                                Sim

   Qual a sua idade? Qual sua identidade de gênero?  \
0                 76                      Homem Cis
1                 23                      Homem Cis
2                 21                     Mulher Cis
3                 21                     Mulher Cis
4                 19                     Mulher Cis

  Em que estado você viveu a maior parte da sua vida?  \
0                                         Pernambuco
1                                     Rio de Janeiro
2                                     Rio de Janeiro
3                                     Rio de Janeiro
4                                     Rio de Janeiro

  Em que estado você vive atualmente?  \
0                      Rio de Janeiro
1                      Rio de Janeiro
2                      Rio de Janeiro
3                      Rio de Janeiro
4                      Rio de Janeiro

  Selecione uma lista para preencher, de preferencia o primeiro item da lista para garantir a aleatoriedade na metodologia.  \
0                                            Lista 3
1                                           Lista 10
2                                            Lista 2
3                                            Lista 4
4                                            Lista 1

  O renê matou todo momento do time cara, que loco filho da puta  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                             Não considero misógina

  “…Na boca de quem não presta\n Pomba gira é vagabunda…”  ...  \
0                                                NaN       ...
1                                                NaN       ...
2                                                NaN       ...
3                                                NaN       ...
4                             Não considero misógina       ...

  não gosta de mim por causa de homem já sei que é vagabunda  \
0                                                NaN
1                                 Considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

  ai gente foda se a militância chamem a vanessa lopes de vagabunda comigoooo  \
0                                                NaN
1                                 Considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

  você eh uma VAGABUNDA você eh uma DESALMADA você eh um CAPETA DEMONIO INFERNO  \
0                                                NaN
1                                 Considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

  “ain sério msm que o flamengo quer falar de roubo” sim piranha e quando roubarem o teu time vc fala do seu ô insuportável do caralho  \
0                                                NaN
1                                 Considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

  Mermao, pessoal ainda tá achando que a Madonna doou 10 milhões\n \n O próprio cara que inventou isso já desmentiu\n \n A Madonna não doou absolutamente NADA, tratou td mundo mal no hotel, falou mal dos brasileiros, pegou os milhões dela e METEU O PÉ\n \n Para de idolatrar essa VACA  \
0                                                NaN
1                                 Considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

  Ué, a galinha mineira jogou o clássico contra o Cruzeiro pelo brasileiro e está jogando contra o Peñarol pela libertadores e não poupou ninguém??  \
0                                                NaN
1                             Não considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

  Lula , Pacheco e essa gangue que ocupou a República tinham de ser recebidos com chuva de merda de vaca e lama pelo povo do Sul.\n Vão la fazer populismo com a\n Desgraça das pessoas.\n A real ? Esse canalhas não estão nem aí.\n Só com a imagem pro Jornal Nacional.  \
0                                                NaN
1                             Não considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

  tem umas fubangas nesse fandom que fazem esforço pra fingir que gostam do justin pq não é possível que você vai conseguir ser uma vaca egoista pra pensar em show e reclamar sobre show enquanto o homem ta virando PAI  \
0                                                NaN
1                                 Considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

  Não aguento mais tanto sofrimento com Tião Galinha e Joaninha  \
0                                                NaN
1                             Não considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

  O VAR SO EXISTE CONTRA O VITÓRIA, INCRÍVEL. \n \n CBF vagabunda
0                                                NaN
1                             Não considero misógina
2                                                NaN
3                                                NaN
4                                                NaN

[5 rows x 308 columns]

<ipython-input-4-cb9bfd7e058c>:8: UserWarning: Parsing dates in %d/%m/%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[coluna_timestamp] = pd.to_datetime(df[coluna_timestamp])

In [ ]:
# prompt: quero que faça uma contagem de cada valor distintos na coluna "Selecione uma lista para preencher, de preferencia o primeiro item da lista para garantir a aleatoriedade na metodologia." dentro do dataset "df_filtrado"

# Realizar a contagem dos valores distintos na coluna especificada do DataFrame filtrado
contagem_valores_distintos = df_filtrado[coluna_selecao].value_counts()

# Exibir a contagem dos valores distintos
print("\nContagem de cada valor distinto na coluna 'Selecione uma lista para preencher...':")
contagem_valores_distintos

Contagem de cada valor distinto na coluna 'Selecione uma lista para preencher...':

Selecione uma lista para preencher, de preferencia o primeiro item da lista para garantir a aleatoriedade na metodologia.
Lista 3     5
Lista 10    5
Lista 2     5
Lista 4     5
Lista 1     5
Lista 9     5
Lista 6     5
Lista 7     5
Lista 5     5
Lista 8     5
Name: count, dtype: int64

In [ ]:
import pandas as pd

# Transforme a segunda base para que cada linha represente um "Tweet" da coluna 9 em diante
df_melted = pd.melt(df_filtrado, id_vars=df_filtrado.columns[:8], var_name='Tweet', value_name='resposta')


# Junte as duas bases de dados com base na coluna "Tweet"
df_final = pd.merge(df_de_para, df_melted, on='Tweet', how='left')


# Reorganize o dataframe final para ter as colunas desejadas: Palavra, Tweet, resposta
#df_final = df_melted[['Palavra', 'Tweet', 'resposta']]

# Salve o dataframe final em um novo arquivo CSV
#df_final.to_csv('terceira_base.csv', index=False)

df_final = df_melted[['Tweet', 'resposta']]
df_final.to_csv('terceira_base.csv', index=False)

print(df_final.head())

                                               Tweet                resposta
0  O renê matou todo momento do time cara, que lo...                     NaN
1  O renê matou todo momento do time cara, que lo...                     NaN
2  O renê matou todo momento do time cara, que lo...                     NaN
3  O renê matou todo momento do time cara, que lo...                     NaN
4  O renê matou todo momento do time cara, que lo...  Não considero misógina

In [ ]:
# prompt: print o volume de valores distintos dentro da coluna "Tweet" no dataset "df_final"

print(f"O volume de valores distintos na coluna 'Tweet' é: {df_final['Tweet'].nunique()}")

O volume de valores distintos na coluna 'Tweet' é: 300

In [ ]:

df_final_sem_nulos = df_final.dropna(subset=['resposta'])

print(df_final_sem_nulos.head())

print(f"O volume de valores distintos na coluna 'Tweet' é: {df_final_sem_nulos['Tweet'].nunique()}")

# Salve o DataFrame sem valores nulos em um novo arquivo CSV (opcional)
#df_final_sem_nulos.to_csv('terceira_base_sem_nulos.csv', index=False)

                                                Tweet                resposta
4   O renê matou todo momento do time cara, que lo...  Não considero misógina
12  O renê matou todo momento do time cara, que lo...  Não considero misógina
15  O renê matou todo momento do time cara, que lo...  Não considero misógina
16  O renê matou todo momento do time cara, que lo...  Não considero misógina
44  O renê matou todo momento do time cara, que lo...  Não considero misógina
O volume de valores distintos na coluna 'Tweet' é: 300

In [ ]:

#tweet_resposta_counts = df_final_sem_nulos.groupby(['Tweet', 'resposta']).size().reset_index(name='counts')
tweet_resposta_counts = df_final.groupby(['Tweet', 'resposta']).size().reset_index(name='counts')

# Exiba a estatística
print(tweet_resposta_counts)

# Salve o DataFrame com as contagens em um novo arquivo CSV (opcional)
tweet_resposta_counts.to_csv('tweet_resposta_counts.csv', index=False)

                                                 Tweet  \
0    "Ain vcs tão comemorando que salvaram um caval...
1    "Ain vcs tão comemorando que salvaram um caval...
2    "Se a Manuela for eleita, vocês vão comer carn...
3    "Se a Manuela for eleita, vocês vão comer carn...
4    "o meu sensor de piriguete explodiu" fala séri...
..                                                 ...
566  “ain sério msm que o flamengo quer falar de ro...
567  “ain sério msm que o flamengo quer falar de ro...
568  “…Na boca de quem não presta\n Pomba gira é va...
569  “…Na boca de quem não presta\n Pomba gira é va...
570  “…Na boca de quem não presta\n Pomba gira é va...

                   resposta  counts
0        Considero misógina       2
1    Não considero misógina       3
2        Considero misógina       2
3    Não considero misógina       3
4        Considero misógina       3
..                      ...     ...
566      Considero misógina       4
567  Não considero misógina       1
568      Considero misógina       2
569  Não considero misógina       2
570         Não sei definir       1

[571 rows x 3 columns]

In [ ]:
# prompt: Dado o dataset "tweet_resposta_counts" com 3 colunas, sendo elas "Tweet", "resposta", "counts", quero que gere uma tabela final com apenas 2 colunas, uma sendo "Tweet" e a outra sendo a coluna resposta. Porém para montar essa regra, vamos classificar cada Tweet baseado nas outras duas colunas. Quero que faça uma classificação onde na situação numero um resposta = "Considero misógina" e counts >= 3 Então retorne  "É Misógina", qual quer resultado diferente disto, retorne "Não misógina". Desta forma esperase uma tabela final com um resultado para cada tweet, o nome das colunas podem ser "Tweet" e "classificação"

def classificar_tweet(row):
    if row['resposta'] == 'Considero misógina' and row['counts'] >= 3:
        return 'É Misógina'
    else:
        return 'Não misógina'

tweet_resposta_counts['classificação'] = tweet_resposta_counts.apply(classificar_tweet, axis=1)

tabela_final = tweet_resposta_counts[['Tweet', 'classificação']].drop_duplicates(subset=['Tweet'])

tabela_final.to_csv('tabela_final.csv', index=False)

tabela_final

                                                 Tweet classificação
0    "Ain vcs tão comemorando que salvaram um caval...  Não misógina
2    "Se a Manuela for eleita, vocês vão comer carn...  Não misógina
4    "o meu sensor de piriguete explodiu" fala séri...    É Misógina
7    *LULA TEM RAZÃO! E ele não está sozinho* A his...  Não misógina
8    *Sana entra no quarto e puxa meu cabelo me jog...    É Misógina
..                                                 ...           ...
560  óbvio que ela sentiu ela tem 15 anos gente ima...    É Misógina
562  “Deixei de fumar ganzas porque a minha namorad...    É Misógina
564  “Vaca”, sons a imitar “mugidos”, insultos rela...    É Misógina
566  “ain sério msm que o flamengo quer falar de ro...    É Misógina
568  “…Na boca de quem não presta\n Pomba gira é va...  Não misógina

[300 rows x 2 columns]